### ISSUE TITLE
Adjusting tunic color eats inputs

### ISSUE THREAD

**Issue by icogn** [hallcristobal/tpgz#20]
Reported by Skyreon in tools-dev at 2020-08-21 12:39 UTC.

Able to recreate: Yes
Version: 0.1a

Go to Tools > Link Tunic Color.
First A press changes color from Green to Blue. Second A press is ignored. Third press works as intended. Fourth is ignored.

The pattern continues and is consistent. Behavior persists if you close the menu (saving where your current position in the cycle was).

**Comment by Pheenoh** [comment]
Fixed in #15
