### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by icogn** [hallcristobal/tpgz#24]
Currently the project has no specified license, which means the following according to GitHub:
> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
-- [GitHub Docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)

This means that any PRs and things like `tpgzw` are in violation of copyright. This is not a huge deal since I don't think anyone plans on taking anyone to court, but it would still be preferable to operate on the right side of the law and have what is and is not allowed clearly laid out.

Based on multiple sources (but most clearly written [here](https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project)), the license can be changed if all existing copyright holders (i.e., contributors) agree to the license change. I think it makes sense to try to do this early on since there are currently only 4 contributors.

As far as which license to use goes, I would suggest [GPLv3](https://choosealicense.com/licenses/gpl-3.0/). Aside from being a solid choice in general, it seems to be the license of choice for new [zsrtp](https://github.com/zsrtp) projects. It would allow us to potentially use [libtp_rel](https://github.com/zsrtp/libtp_rel), and I think this might incentivize all of the TP project developers to work more closely together.

I would be willing to make an illegal PR to add the license, but I think we need everyone to agree first.

Opening for discussion.

**Comment by Pheenoh** [comment]
Fixed in #25
