### ISSUE TITLE
Font Issues

### ISSUE THREAD

**Issue by Pheenoh** [hallcristobal/tpgz#54]
Building new fonts is broken on the latest nightly rust toolchain for x86_64. I'm not sure what the version is that the break happens in but it functions correctly using `nightly-2019-07-08`.

So we need to either update the BUILDING.md to include this:

`rustup override set nightly-2019-07-08`

Or if someone wants to port it to python since that's what all the other external tooling is being built in, that would be awesome too.

**Comment by kipcode66** [comment]
I was gonna redo the fonts anyway xD I'll make it into a python script then.
